### ISSUE TITLE
Add build for Cassandra 3.11.7 and fix Cassandra 3.11.6 build

### ISSUE THREAD

**Issue by johntrimble** [datastax/management-api-for-apache-cassandra#38]
Currently, Cassandra 3.11.6 is built and pushed to its own repo in dockerhub:

```
      - name: Publish 3.11 to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: datastax/cassandra-mgmtapi-3_11_6
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_names: true
          dockerfile: Dockerfile-3_11
```

However, the Dockerfile-3_11 file use the broader `cassandra:3.11` base image:

```
FROM management-api-for-apache-cassandra-builder as builder

FROM cassandra:3.11
```

This means that if we were to create a new release today, we'd end up with a Cassandra 3.11.7 image in the datastax/cassandra-mgmtapi-3_11_6 repo, which is probably not what we want--though it is a nice way to sneak in upgrade.

We should, at a minimum, not push a 3.11.7 Cassandra image masquerading as 3.11.6. Talking to @jimdickinson, I think there is room to debate whether or not we should support both 3.11.6 and 3.11.7 or just the latest 3.11.x for future versions of the management API. If it's easy, I'd personally just support both for now to make navigating the change control processes at enterprises easier.
